# Generated by Django 4.2.1 on 2023-05-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recaudacion',
            name='concepto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
