# Generated by Django 4.2.1 on 2023-05-30 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_cita_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recaudacion',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.medico'),
        ),
    ]
