# Generated by Django 4.2.1 on 2023-05-30 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_recaudacion_fecha_alter_cita_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recaudacion',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.medico'),
        ),
    ]
