# Generated by Django 4.2.1 on 2023-05-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_recaudacion_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
