# Generated by Django 4.2.1 on 2023-05-31 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_medico_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='medico_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
