# Generated by Django 4.2.1 on 2023-05-31 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cita_antecedentes_clinicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='antecedentes_clinicos',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='medico_id',
        ),
        migrations.AddField(
            model_name='recaudacion',
            name='cita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cita'),
        ),
        migrations.AlterField(
            model_name='recaudacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
